from __future__ import annotations
from typing import Any

class FormBuilderManifest:
    def __init__(self, operation: str = "create", fields: Any = None) -> None:
        self.operation = operation
        self.fields = fields or []

    def to_dict(self) -> dict[str, Any]:
        return {
            "operation": self.operation,
            "fields": self.fields
        }

class FormBuilder:
    WIDGET_MAP = {
        "text": "text",
        "textarea": "textarea",
        "integer": "number",
        "decimal": "number",
        "date": "date",
        "datetime": "datetime",
        "boolean": "checkbox",
        "enum": "select",
        "json": "json",
        "uuid": "text"
    }
    SYSTEM_FIELDS = {
        "id",
        "created_at",
        "updated_at",
        "deleted_at"
    }
    def __init__(self, operation: str = "create") -> None:
        self.operation = operation

    def build(self, schema: dict[str, dict[str, Any]]) -> dict[str, Any]:
        fields: list[dict[str, Any]] = []
        for field in schema.values():
            if self._should_skip(field):
                continue
            fields.append(
                self.build_field(field)
            )
        return {
            "operation": self.operation,
            "fields": fields
        }
    def _should_skip(self, field: dict[str, Any]) -> bool:
        if field["name"] in self.SYSTEM_FIELDS:
            return True
        if field.get("autogenerated", False):
            return True
        if field.get("readonly", False):
            return True
        return False

    def build_field(self, field: dict[str, Any]) -> dict[str, Any]:
        result: dict[str, Any] = {
            "name": field["name"],
            "label": field["label"],
            "widget": self.WIDGET_MAP.get(
                field["type"],
                "text"
            ),
            "required": field["required"],
            "nullable": field["nullable"],
            "data": field.get("data"),
            "default": field.get("default")
        }
        if field.get("max_length"):
            result["max_length"] = field["max_length"]
        if field.get("precision"):
            result["precision"] = field["precision"]
        if field.get("scale"):
            result["scale"] = field["scale"]
        if field["type"] == "enum":
            result["options"] = field["choices"]
        if field.get("foreign_key"):
            result["foreign_key"] = field["foreign_key"]
        return result