from typing import Any

class SchemaBuilder:

    TYPE_MAP = {
        "character varying": "text",
        "text": "textarea",
        "smallint": "integer",
        "integer": "integer",
        "bigint": "integer",
        "numeric": "decimal",
        "real": "decimal",
        "double precision": "decimal",
        "boolean": "boolean",
        "date": "date",
        "timestamp without time zone": "datetime",
        "timestamp with time zone": "datetime",
        "time without time zone": "time",
        "time with time zone": "time",
        "json": "json",
        "jsonb": "json",
        "uuid": "uuid"
    }


    def __init__(self, raw: dict[str, Any], enums: dict[str, list[str]] | None = None) -> None:
        self.raw = raw
        self.enums = enums or {}


    def build(self) -> dict[str, dict[str, Any]]:

        schema: dict[str, dict[str, Any]] = {}

        primary_keys = self._primary_keys()
        unique_columns = self._unique_columns()
        indexed_columns = self._indexed_columns()
        foreign_keys = self._foreign_keys()
        comments = self._comments()


        for column in self.raw["columns"]:

            name = column["column_name"]

            field = {

                "name": name,

                "label": (
                    comments.get(name)
                    or name.replace("_", " ").title()
                ),

                "type": self._resolve_type(column),


                "nullable": (
                    column["is_nullable"] == "YES"
                ),

                "required": (
                    column["is_nullable"] == "NO"
                ),


                "default": (
                    self._normalize_default(
                        column["column_default"]
                    )
                ),


                "primary_key": (
                    name in primary_keys
                ),

                "unique": (
                    name in unique_columns
                ),

                "indexed": (
                    name in indexed_columns
                ),


                "readonly": (
                    self._is_readonly(column, name in primary_keys)
                ),

                "autogenerated": (
                    self._is_autogenerated(column, name in primary_keys)
                ),


                "max_length": (
                    column["character_maximum_length"]
                ),

                "precision": (
                    column["numeric_precision"]
                ),

                "scale": (
                    column["numeric_scale"]
                ),


                "postgres": {

                    "data_type":
                        column["data_type"],

                    "udt_name":
                        column["udt_name"]
                }
            }

            if field["type"] == "enum":

                enum_name = column["udt_name"]

                field["enum_name"] = enum_name

                field["choices"] = (
                    self.enums.get(
                        enum_name,
                        []
                    )
                )
            if name in foreign_keys:

                fk = foreign_keys[name]

                field["foreign_key"] = fk

                field["relation"] = {

                    "type": "select",

                    "source": {

                        "schema":
                            fk["schema"],

                        "table":
                            fk["table"],

                        "value":
                            fk["column"]
                    }
                }


            schema[name] = field


        return schema



    def _resolve_type(self, column):

        if column["data_type"] == "USER-DEFINED":
            return "enum"


        return self.TYPE_MAP.get(
            column["data_type"],
            "text"
        )



    def _primary_keys(self) -> set[str]:

        pk = self.raw.get(
            "primary_key"
        )

        if not pk:
            return set()

        if isinstance(pk, dict):
            if "columns" in pk:
                columns = pk["columns"]
            elif "column_name" in pk:
                columns = [pk["column_name"]]
            else:
                columns = list(pk.values())
        elif isinstance(pk, (list, tuple, set)):
            columns = []
            for item in pk:
                if isinstance(item, dict):
                    if "columns" in item:
                        columns.extend(item["columns"])
                    elif "column_name" in item:
                        columns.append(item["column_name"])
                    else:
                        columns.extend(item.values())
                else:
                    columns.append(item)
        else:
            columns = [pk]

        return {
            column
            for column in columns
            if column is not None
        }



    def _unique_columns(self):

        unique = set()


        for row in self.raw.get(
            "unique_constraints",
            []
        ):

            unique.add(
                row["column_name"]
            )


        for index in self.raw.get(
            "unique_indexes",
            []
        ):

            unique.update(
                index["columns"]
            )


        return unique



    def _indexed_columns(self):

        indexed = set()


        for idx in self.raw.get(
            "indexes",
            []
        ):

            indexed.update(
                idx["columns"]
            )


        return indexed



    def _foreign_keys(self):

        return {

            row["column_name"]: {

                "schema":
                    row["foreign_schema"],

                "table":
                    row["foreign_table"],

                "column":
                    row["foreign_column"]

            }

            for row in self.raw.get(
                "foreign_keys",
                []
            )
        }



    def _comments(self):

        return {

            row["column_name"]:
                row["comment"]

            for row in self.raw.get(
                "comments",
                []
            )

            if row["comment"]

        }



    def _is_autogenerated(self, column: dict[str, Any], primary_key: bool = False) -> bool:
        default = column.get("column_default")
        data_type = column.get("data_type", "")
        udt_name = column.get("udt_name", "")

        serial_like = any(
            token in data_type.lower()
            for token in ("serial", "bigserial", "smallserial")
        ) or any(
            token in udt_name.lower()
            for token in ("serial", "bigserial", "smallserial")
        )

        return (
            serial_like
            or (
                default
                and default.startswith("nextval(")
            )
            or (
                column.get("is_identity") == "YES"
            )
        )
    
    def _is_readonly(self, column: dict[str, Any], primary_key: bool = False) -> bool:
        default = column.get("column_default")
        return (
            self._is_autogenerated(
                column,
                primary_key=primary_key
            )
            or
            (
                default
                and "now()" in default
            )
        )

    def _normalize_default(self, value):
        if value is None:
            return None
        # No retornar valores de secuencias (son internos de la BD)
        if value.startswith("nextval("):
            return None

        if "::" in value:

            value = value.rsplit(
                "::",
                1
            )[0]


        return value.strip("'")