from .query import Query
from ..utils.errors import (
    MissingRequiredFieldsError,
    MissingValuesError,
    ValueCountMismatchError,
)
from typing import Any


class Insert(Query):
    operation = "insert"

    def __init__(self, table: Any, fields: tuple[Any, ...] | None = None) -> None:
        super().__init__(table, fields)
        self._values = ()

    def values(self, *values: Any) -> "Insert":
        if len(values) == 1 and isinstance(values[0], dict):
            payload = values[0]
            schema = getattr(self.table, "schema", {}) or {}
            expected_fields = self._resolved_fields(include_nullable=True)
            field_names = tuple(self._field_name(field) for field in expected_fields)

            validator = self._expected_data(field_names, schema)
            validation = validator.validate(payload)
            if not validation["valid"]:
                details = "; ".join(
                    f"{item['field']}:{item['code']}" for item in validation["errors"]
                )
                raise ValueError(details)

            captured = validator.data()
            self._fields = tuple(
                field for field in expected_fields
                if self._field_name(field) in captured
            )
            self._values = tuple(captured[self._field_name(field)] for field in self._fields)
            return self

        if self._fields and not (len(self._fields) == 1 and self._fields[0] == "*"):
            expected_fields = self._resolved_fields(include_nullable=True)
            expected_count = len(expected_fields)
        elif values:
            expected_fields = self._fields or ()
            expected_count = len(values)
        else:
            expected_fields = self._resolved_fields(include_nullable=True)
            expected_count = len(expected_fields)

        if values and len(values) != expected_count:
            field_names = ", ".join(map(str, expected_fields)) if expected_fields else "none"
            # raise ValueError(
            #     f"Expected {expected_count} values for writable columns [{field_names}], got {len(values)}"
            # )
            raise ValueCountMismatchError()

        self._values = values
        return self

    def _resolved_fields(self, include_nullable: bool = False) -> tuple[Any, ...]:
        schema = getattr(self.table, "schema", {}) or {}

        def is_writable(name, meta):
            if meta.get("autogenerated", False):
                return False
            if meta.get("readonly", False):
                return False
            if not include_nullable and meta.get("nullable", True):
                return False
            return True

        if not self._fields:
            return tuple(
                name for name, meta in schema.items()
                if is_writable(name, meta)
            )

        if len(self._fields) == 1 and self._fields[0] == "*":
            return tuple(
                name for name, meta in schema.items()
                if is_writable(name, meta)
            )

        return tuple(
            field for field in self._fields
            if self._field_name(field) not in schema
            or is_writable(self._field_name(field), schema[self._field_name(field)])
        )

    def _required_non_autogenerated_fields(self, fields: tuple[Any, ...] | None = None) -> tuple[Any, ...]:
        schema = getattr(self.table, "schema", {}) or {}

        def is_required(name, meta):
            explicit_required = (
                "required" in meta
                or "autogenerated" in meta
                or "readonly" in meta
                or "default" in meta
            )
            return (
                explicit_required
                and not meta.get("autogenerated", False)
                and not meta.get("readonly", False)
                and not meta.get("nullable", True)
                and meta.get("default") is None
            )

        if fields is None:
            return tuple(
                name for name, meta in schema.items()
                if is_required(name, meta)
            )

        return tuple(
            name for name in fields
            if is_required(
                self._field_name(name),
                schema.get(self._field_name(name), {}),
            )
        )

    def sql(self) -> str:
        self._reset_params()

        if not self._values:
            if self._fields and len(self._fields) == 1 and self._fields[0] == "*":
                required_fields = self._required_non_autogenerated_fields()
                if required_fields:
                    raise MissingRequiredFieldsError()
                return f"INSERT INTO {self.table} DEFAULT VALUES"

            fields = self._resolved_fields(include_nullable=False)
            if not fields:
                return f"INSERT INTO {self.table} DEFAULT VALUES"

            required_fields = self._required_non_autogenerated_fields(fields)
            if required_fields:
                # raise MissingRequiredFieldsError(
                #     "Hay columnas no automáticas y no nulas; debe proporcionar valores para insertarlas."
                # )
                raise MissingRequiredFieldsError()

            return f"INSERT INTO {self.table} DEFAULT VALUES"

        fields = self._resolved_fields(include_nullable=True)

        if not fields:
            return f"INSERT INTO {self.table} DEFAULT VALUES"

        if len(self._values) != len(fields):
            # raise ValueError(
            #     "INSERT values missing"
            # )
            raise MissingValuesError()

        columns = ", ".join(map(str, fields))

        placeholders = ", ".join(
            ["%s"] * len(fields)
        )

        self._params.extend(
            self._values
        )

        template = (
            f"INSERT INTO {self.table} "
            f"({columns}) "
            f"VALUES ({placeholders})"
        )

        return template