from __future__ import annotations

from dataclasses import dataclass, asdict
from typing import Any, TYPE_CHECKING

from ..sql_objects.condition import Condition, CompoundCondition
from ..sql_objects.field import Field
from cheap_render.cheap_render import render_page
from expected_data.expected_data import ExpectedData, Field as ExpectedField #type:ignore
from ..builders.form_builder import FormBuilder

if TYPE_CHECKING:
    from sql_objects.table import Table

#la plantilla está así: 
#Operation: http-method, http successful expected code, http error expected code

@dataclass(frozen=True)
class HttpMeta:
    method: str
    expected_success: int
    expected_error: int

operations_httpinf = {
    "update": asdict(HttpMeta("PUT", 200, 400)),
    "select": asdict(HttpMeta("GET", 200, 404)),
    "delete": asdict(HttpMeta("DELETE", 204, 404)),
    "insert": asdict(HttpMeta("POST", 201, 400)),
}

class Query:
    operation = "query"

    def __init__(self, table: "Table", fields: tuple[Any, ...] | None = None) -> None:
        self.table = table
        self._executor = getattr(table, "sql", None)
        self._fields = tuple(fields or ())
        #pareciera que todos los _my se volvieron información de la query
        self._mymeta = QueryManifest(self)
        self._myoperationhttpinf = operations_httpinf[self.operation]

        self._params = []

        self._condition = None
        self._from_query = None
        self._from_alias = None
        self._joins = []
        self._order_by = []
        self._group_by = []

        self._limit = None
        self._offset = None
        self._distinct = False

    def params(self) -> tuple[Any, ...]:
        return tuple(self._params)

    def _reset_params(self) -> None:
        self._params = []

    @staticmethod
    def _field_name(field: Any) -> str:
        return field if isinstance(field, str) else field.name

    @staticmethod
    def _schema_datatype(definition: dict[str, Any]) -> Any:
        datatypes = {
            "text": str,
            "textarea": str,
            "integer": int,
            "decimal": (int, float),
            "boolean": bool,
            "uuid": str,
        }
        return definition.get("datatype") or datatypes.get(
            definition.get("type")
        )

    def _expected_data(
        self,
        field_names: tuple[Any, ...],
        schema: dict[str, dict[str, Any]],
    ) -> ExpectedData:
        fields = {}
        for field in field_names:
            name = self._field_name(field)
            definition = schema.get(name, {})
            fields[name] = ExpectedField(
                key=name,
                required=definition.get("required", False),
                nullable=definition.get("nullable", True),
                datatype=self._schema_datatype(definition),
                min_length=definition.get("min_length"),
                max_length=definition.get("max_length"),
                default=definition.get("default"),
                enum=definition.get("choices") or definition.get("enum"),
                scanner=definition.get("scanner"),
                autogenerated=definition.get("autogenerated", False),
                readonly=definition.get("readonly", False),
            )
        return ExpectedData(fields)

    def fields(self, *fields):
        self._fields = tuple(fields)
        return self

    def where(self, condition):
        self._condition = condition
        return self

    def from_subquery(self, query: Any, alias: str | None = None) -> "Query":
        self._from_query = query
        self._from_alias = alias
        return self

    @property
    def has_where(self) -> bool:
        return self._condition is not None

    # CONDITIONS

    def _compile_condition(self, condition):
        if isinstance(condition, CompoundCondition):
            left = self._compile_condition(condition.left)
            right = self._compile_condition(condition.right)
            return f"({left} {condition.operator} {right})"

        value = condition.value

        if self._is_query_like(value):
            sub_sql = value.sql()
            sub_params = tuple(value.params())
            if sub_params:
                self._params.extend(sub_params)
            if condition.operator == "IN":
                return f"{condition.column} IN ({sub_sql})"
            return f"{condition.column} {condition.operator} ({sub_sql})"

        if isinstance(value, Field):
            return f"{condition.column} {condition.operator} {value}"

        if condition.value is None and condition.operator in {"=", "==", "!=", "<>"}:
            operator = "IS" if condition.operator in {"=", "=="} else "IS NOT"
            return f"{condition.column} {operator} NULL"

        if condition.operator == "IN":
            values = list(value)

            if not values:
                return "FALSE"

            placeholders = ",".join(["%s"] * len(values))
            self._params.extend(values)
            return f"{condition.column} IN ({placeholders})"

        self._params.append(value)
        return f"{condition.column} {condition.operator} %s"

    def _compile_where(self):
        if self._condition is None:
            return ""

        return " WHERE " + self._compile_condition(self._condition)

    # JOINS

    def join(self, table, condition, join_type="INNER"):
        if join_type.upper() not in {"INNER", "LEFT", "RIGHT", "FULL", "CROSS"}:
            raise ValueError("Unsupported join type")
        self._joins.append((join_type, table, condition))
        return self

    def _compile_joins(self):
        if not self._joins:
            return ""

        result = []
        for join_type, table, condition in self._joins:
            if isinstance(condition, (Condition, CompoundCondition)):
                condition_sql = self._compile_condition(condition)
            else:
                condition_sql = str(condition)
            result.append(f"{join_type.upper()} JOIN {table} ON {condition_sql}")

        return " " + " ".join(result)

    def _is_query_like(self, value: Any) -> bool:
        return hasattr(value, "sql") and hasattr(value, "params")

    def _compile_from(self) -> str:
        if self._from_query is not None:
            sub_sql = self._from_query.sql()
            sub_params = tuple(self._from_query.params())
            if sub_params:
                self._params.extend(sub_params)
            alias_sql = f" AS {self._from_alias}" if self._from_alias else ""
            return f"FROM ({sub_sql}){alias_sql}"

        return f"FROM {self.table}"

    # ORDER y GROUP

    def order_by(self, *fields):
        self._order_by = fields
        return self

    def _compile_order_by(self):
        if not self._order_by:
            return ""

        return " ORDER BY " + ", ".join(map(str, self._order_by))

    def group_by(self, *fields: Any) -> "Query":
        self._group_by = fields
        return self

    def _compile_group_by(self):
        if not self._group_by:
            return ""

        return " GROUP BY " + ", ".join(map(str, self._group_by))

    # PAGINATION

    def limit(self, amount: int) -> "Query":
        self._limit = amount
        return self

    def offset(self, amount: int) -> "Query":
        self._offset = amount
        return self

    def _compile_limit(self):
        return f" LIMIT {self._limit}" if self._limit is not None else ""

    def _compile_offset(self):
        return f" OFFSET {self._offset}" if self._offset is not None else ""

    # SELECT

    def distinct(self, enabled=True):
        self._distinct = enabled
        return self

    def _compile_distinct(self):
        return "DISTINCT " if self._distinct else ""

    def _compile_fields(self):
        if not self._fields:
            return "*"

        if any(isinstance(field, str) and field == "*" for field in self._fields):
            return "*"

        return ", ".join(map(str, self._fields))

    def sql(self):
        raise NotImplementedError

    # @property
    # def db(self):
    #     return self._executor or getattr(self.table, "sql", None)

    def execute(self, fetchone: bool = False, fetchall: bool = False, commit: bool = False) -> Any:
        if self._executor is None:
            raise TypeError("No executor attached to query")

        return self._executor.execute(
            self.sql(),
            params=self.params(),
            fetchone=fetchone,
            fetchall=fetchall,
            commit=commit
        )

    # RESPONSABILIDADES DEL FORM - ES NECESARIO NO MEZCLAR COSAS

    def meta(self, schema: Any = None, operation: str | None = None, include_query: bool = False) -> dict[str, Any]:
        return self._mymeta.build(
            schema=schema,
            operation=operation,
            include_query=include_query
        )
    
    def form_schema(
        self,
        #form_id=None,
        #schema=None,
        #operation=None,
        formname: str | None = None,
        style_path: str | None = None,
        script_path: str | None = None,
    ) -> dict[str, Any]:

        #Ha evolucionado el form_schema, que ahora muestra info http del form

        manifest = self.meta(include_query=False)
        default_formname = formname or f"SQL {self.operation.upper()} FORM"

        return {
            "operation_httpinf": self._myoperationhttpinf,
            "title": default_formname,
            #"color": "#2d6cdf",
            "formname": default_formname,
            "style_path": style_path,
            "script_path": script_path,
            "fields": manifest["fields"]
            #"formid": form_id
        }

    #Esta función sólo la puse por solidaridad y mvp STINKY METHOD
    def html_render(self, formname: str | None = None) -> str:
        form_schema = self.form_schema(
            formname=formname, 
            style_path="/static/myform.css", 
            script_path="/static/myform.js"
        )

        return render_page(
            form_schema,
            formname=form_schema["formname"],
        )

    # METADATA

    @property
    def query_fields(self):
        return {
            field.name
            for field in self._fields
            if isinstance(field, Field)
        }
    @property
    def condition_fields(self):
        def collect(cond):
            if isinstance(cond, CompoundCondition):
                return collect(cond.left) | collect(cond.right)

            if isinstance(cond, Condition):
                if isinstance(cond.column, Field):
                    return {cond.column.name}

            return set()

        if self._condition is None:
            return set()

        return collect(self._condition)
    def debug_sql(self):
        return self._interpolate_sql(self.sql())
    def _quote_value(self, value):
        if value is None:
            return "NULL"
        if isinstance(value, bool):
            return "TRUE" if value else "FALSE"
        if isinstance(value, (int, float)):
            return str(value)
        if isinstance(value, str):
            escaped = value.replace("'", "''")
            return f"'{escaped}'"
        return str(value)
    def _interpolate_sql(self, sql_template):
        params = self.params()
        if not params:
            return sql_template

        result = sql_template
        for param in params:
            result = result.replace("%s", self._quote_value(param), 1)

        return result


class QueryManifest:
    def __init__(self, query):
        self.query = query
        self.meta = {}

    def build(self, schema=None, operation=None, include_query=False):
        query = self.query

        if operation is None:
            operation = query.operation

        builder = FormBuilder(operation=operation)
        self.builder = builder

        if schema is None:
            schema = getattr(query.table, "schema", {})

        current_data = {}

        if operation == "update" and query.has_where:
            current_data = self._load_form_data(
                schema,
                builder,
            )

        manifest = {
            "meta": self._build_meta(operation),
            "fields": self._build_fields(
                schema,
                current_data,
                builder,
            ),
        }

        if include_query:
            manifest["query"] = self._build_query_manifest(
                schema,
                operation,
                builder,
            )

        return manifest


    def _build_meta(self, operation):
        return {
            "operation": operation,
            **self.meta,
        }

    def _build_fields(self, schema, current_data, builder):
        query = self.query

        fields = []

        use_schema_fields = (
            query._fields
            and len(query._fields) == 1
            and query._fields[0] == "*"
        )

        if use_schema_fields:
            definitions = schema.values()

        else:
            field_names = self._form_field_names()

            if field_names:
                definitions = []

                for name in field_names:
                    if name in schema:
                        definitions.append(schema[name])
                    else:
                        definitions.append({
                            "name": name,
                            "label": name.replace("_", " ").title(),
                            "type": "text",
                            "required": False,
                            "nullable": True,
                        })

            else:
                definitions = schema.values()


        for definition in definitions:
            if builder._should_skip(definition):
                continue

            definition = dict(definition)

            field_name = definition.get("name")

            if field_name in current_data:
                definition["data"] = current_data[field_name]

            fields.append(
                builder.build_field(definition)
            )

        return fields

    def _build_query_manifest(self, schema, operation, builder):
        query = self.query

        if (
            operation == "update"
            and getattr(query, "_values", ()) == ()
            and query.has_where
        ):
            select_fields = self._select_fields(schema, builder)

            if select_fields:
                sql, params = self._build_select_for_form(
                    select_fields
                )

                return {
                    "sql": sql,
                    "params": params,
                }


        return {
            "sql": query.sql(),
            "params": query.params(),
        }

    def _load_form_data(self, schema, builder):
        query = self.query

        if query._executor is None:
            return {}

        select_fields = self._select_fields(schema, builder)

        if not select_fields:
            return {}

        sql, params = self._build_select_for_form(
            select_fields
        )

        row = query._executor.execute(
            sql,
            params=params,
            fetchone=True,
        )

        if not row:
            return {}

        return {
            key: row.get(key)
            for key in row.keys()
            if key in select_fields
        }

    def _select_fields(self, schema, builder):
        query = self.query

        use_schema_fields = (
            query._fields
            and len(query._fields) == 1
            and query._fields[0] == "*"
        )

        if use_schema_fields:
            return [
                definition.get("name")
                for definition in schema.values()
                if not builder._should_skip(definition)
                and definition.get("name")
            ]

        return self._form_field_names()

    def _build_select_for_form(self, select_fields):
        query = self.query

        columns = ", ".join(select_fields)

        original_params = list(query._params)

        query._params = []

        where_sql = query._compile_where()

        params = tuple(query._params)

        query._params = original_params

        return (
            f"SELECT {columns} FROM {query.table}{where_sql}",
            params,
        )

    def _form_field_names(self):
        query = self.query

        names = []
        seen = set()

        for name in query.query_fields:
            if name not in seen:
                seen.add(name)
                names.append(name)

        for name in query.condition_fields:
            if name not in seen:
                seen.add(name)
                names.append(name)

        return names