#Checar cambios aquí respecto a ExpectedData
from .query import Query
from ..utils.errors import ValueCountMismatchError, MissingFieldsError, MissingConditionError, MissingWritableFieldsError, MissingValuesError
from typing import Any

class Update(Query):
    operation = "update"

    def __init__(self, table: Any, fields: tuple[Any, ...] | None = None) -> None:
        super().__init__(table, fields)
        self._values = ()

    def values(self, *values: Any) -> "Update":
        if len(values) == 1 and isinstance(values[0], dict):
            payload = values[0]
            schema = getattr(self.table, "schema", {}) or {}
            expected_fields = self._resolved_fields(include_nullable=True)
            field_names = tuple(self._field_name(field) for field in expected_fields)

            validator = self._expected_data(field_names, schema)
            validation = validator.validate(payload)
            if not validation["valid"]:
                details = "; ".join(
                    f"{item['field']}:{item['code']}" for item in validation["errors"]
                )
                raise ValueError(details)

            captured = validator.data()
            self._fields = tuple(
                field for field in expected_fields
                if self._field_name(field) in captured
            )
            self._values = tuple(captured[self._field_name(field)] for field in self._fields)
            return self

        if self._fields and not (len(self._fields) == 1 and self._fields[0] == "*"):
            expected_fields = self._resolved_fields(include_nullable=True)
            expected_count = len(expected_fields)
        else:
            expected_fields = self._resolved_fields(include_nullable=True)
            expected_count = len(expected_fields)

        if values and len(values) != expected_count:
            # field_names = ", ".join(map(str, expected_fields)) if expected_fields else "none"
            # raise ValueError(
            #     f"Expected {expected_count} values for writable columns [{field_names}], got {len(values)}"
            # )
            raise ValueCountMismatchError()

        self._values = values
        return self

    def _resolved_fields(self, include_nullable: bool = False) -> tuple[Any, ...]:
        schema = getattr(self.table, "schema", {}) or {}

        def is_writable(name, meta):
            if meta.get("autogenerated", False):
                return False
            if meta.get("readonly", False):
                return False
            if not include_nullable and meta.get("nullable", True):
                return False
            return True

        if not self._fields:
            return tuple(
                name for name, meta in schema.items()
                if is_writable(name, meta)
            )

        if len(self._fields) == 1 and self._fields[0] == "*":
            return tuple(
                name for name, meta in schema.items()
                if is_writable(name, meta)
            )

        return tuple(
            field for field in self._fields
            if self._field_name(field) not in schema
            or is_writable(self._field_name(field), schema[self._field_name(field)])
        )

    def sql(self) -> str:
        if not self._fields:
            raise MissingFieldsError()

        if not self.has_where:
            #raise ValueError("Unsafe UPDATE without WHERE")
            raise MissingConditionError()

        fields = self._resolved_fields(include_nullable=True)

        if not fields:
            raise MissingFieldsError()

        if len(self._values) != len(fields):
            # raise ValueError(
            #     "UPDATE values missing"
            # )
            raise MissingValuesError()

        self._reset_params()

        set_clause = ", ".join(
            f"{field} = %s"
            for field in fields
        )

        self._params.extend(
            self._values
        )

        where = self._compile_where()

        template = (
            f"UPDATE {self.table} "
            f"SET {set_clause}"
            f"{where}"
        )

        return template