from __future__ import annotations

from typing import TYPE_CHECKING, Any

from .column_namespace import ColumnNamespace
from ..builders.schema_builder import SchemaBuilder

from ..sql_operations.update import Update
from ..sql_operations.insert import Insert
from ..sql_operations.select import Select
from ..sql_operations.delete import Delete

if TYPE_CHECKING:
    from sql_operations.query import Query


class Table:
    def __init__(self, sql: Any, tablename: str) -> None:
        self.sql = sql
        self.tablename = tablename

    def __str__(self) -> str:
        if hasattr(self, "_alias"):
            return f"{self.tablename} AS {self._alias}"
        return self.tablename

    @property
    def column(self) -> ColumnNamespace:
        if not hasattr(self, "_columns"):
            self._columns = ColumnNamespace(self)
        return self._columns
    
    @property
    def information(self) -> dict[str, Any]:
        if not hasattr(self, "_information"):
            self._information = {
                "columns": self._get_columns(),
                "constraints": self._get_constraints(),
                "foreign_keys": self._get_foreign_keys(),
                "primary_key": self._get_primary_key(),
                "unique_constraints": self._get_unique_constraints(),
                "indexes": self._get_indexes(),
                "comments": self._get_column_comments(),
            }
        return self._information

    @property
    def raw(self) -> dict[str, Any]:
        return self.information

    @property
    def schema(self) -> dict[str, dict[str, Any]]:
        if not hasattr(self, "_schema"):
            self._schema = SchemaBuilder(
                self.raw,
                self.sql.enums
            ).build()
        return self._schema

    def alias(self, name: str) -> "Table":
        # mejor no mutar self
        clone = Table(self.sql, self.tablename)
        clone._alias = name
        return clone

    def create(self, columns: dict[str, Any] | None = None, if_not_exists: bool = True, replace: bool = False) -> "Table":
        self.sql.create_table(
            tablename=self.tablename,
            columns=columns,
            if_not_exists=if_not_exists,
            replace=replace
        )
        return self

    def select(self, *fields: Any) -> Select:
        return Select(self, self._normalize_fields(fields))

    def insert(self, *fields: Any) -> Insert:
        return Insert(self, self._normalize_fields(fields))

    def update(self, *fields: Any) -> Update:
        return Update(self, self._normalize_fields(fields))

    def delete(self, *fields: Any) -> Delete:
        return Delete(self, self._normalize_fields(fields) if fields else None)

    def _normalize_fields(self, fields: tuple[Any, ...] | None) -> tuple[Any, ...] | None:
        if fields is None:
            return None

        normalized = []
        for field in fields:
            if isinstance(field, str):
                if not field.strip():
                    continue
                if field == "*":
                    return ("*",)
                normalized.append(self.c[field])
            else:
                normalized.append(field)

        return tuple(normalized)

    @staticmethod
    def is_autogenerated(column: dict[str, Any]) -> bool:
        return (
            (
                column.get("column_default")
                and column["column_default"].startswith("nextval(")
            )
            or column.get("is_identity") == "YES"
        )

    def _get_columns(self) -> list[dict[str, Any]]:
        return self.sql.fetchall("""
            SELECT ordinal_position, column_name, data_type, udt_name,
                   is_nullable, column_default, is_identity,
                   identity_generation, character_maximum_length,
                   numeric_precision, numeric_scale
            FROM information_schema.columns
            WHERE table_schema = %s
              AND table_name = %s
            ORDER BY ordinal_position;
        """, (self.sql.namespace, self.tablename))

    def _get_constraints(self) -> list[dict[str, Any]]:
        return self.sql.fetchall("""
            SELECT con.conname AS constraint_name,
                   con.contype AS constraint_type,
                   a.attname AS column_name,
                   pg_get_constraintdef(con.oid) AS definition
            FROM pg_constraint con
            JOIN pg_class rel ON rel.oid = con.conrelid
            JOIN pg_namespace n ON n.oid = rel.relnamespace
            LEFT JOIN unnest(con.conkey) WITH ORDINALITY AS cols(attnum, ord)
                ON TRUE
            LEFT JOIN pg_attribute a
                ON a.attnum = cols.attnum
               AND a.attrelid = rel.oid
            WHERE n.nspname = %s
              AND rel.relname = %s;
        """, (self.sql.namespace, self.tablename))

    def _get_foreign_keys(self) -> list[dict[str, Any]]:
        return self.sql.fetchall("""
            SELECT tc.constraint_name,
                   kcu.column_name,
                   ccu.table_schema AS foreign_schema,
                   ccu.table_name AS foreign_table,
                   ccu.column_name AS foreign_column
            FROM information_schema.table_constraints tc
            JOIN information_schema.key_column_usage kcu
              ON tc.constraint_name = kcu.constraint_name
             AND tc.table_schema = kcu.table_schema
            JOIN information_schema.constraint_column_usage ccu
              ON ccu.constraint_name = tc.constraint_name
             AND ccu.table_schema = tc.table_schema
            WHERE tc.constraint_type = 'FOREIGN KEY'
              AND tc.table_schema = %s
              AND tc.table_name = %s;
        """, (self.sql.namespace, self.tablename))

    def _get_primary_key(self) -> dict[str, Any] | None:
        return self.sql.fetchone("""
            SELECT a.attname AS column_name
            FROM pg_index i
            JOIN pg_attribute a
              ON a.attnum = ANY(i.indkey)
             AND a.attrelid = i.indrelid
            JOIN pg_class c ON c.oid = i.indrelid
            JOIN pg_namespace n ON n.oid = c.relnamespace
            WHERE i.indisprimary
              AND n.nspname = %s
              AND c.relname = %s;
        """, (self.sql.namespace, self.tablename))

    def _get_unique_constraints(self) -> list[dict[str, Any]]:
        return self.sql.fetchall("""
            SELECT con.conname,
                   a.attname AS column_name
            FROM pg_constraint con
            JOIN pg_class rel ON rel.oid = con.conrelid
            JOIN pg_namespace n ON n.oid = rel.relnamespace
            CROSS JOIN LATERAL unnest(con.conkey) AS cols(attnum)
            JOIN pg_attribute a
              ON a.attnum = cols.attnum
             AND a.attrelid = rel.oid
            WHERE con.contype = 'u'
              AND n.nspname = %s
              AND rel.relname = %s;
        """, (self.sql.namespace, self.tablename))

    def _get_indexes(self) -> list[dict[str, Any]]:
        return self.sql.fetchall("""
            SELECT i.relname AS index_name,
                   ix.indisunique AS is_unique,
                   ix.indisprimary AS is_primary,
                   array_agg(a.attname ORDER BY k.ordinality) AS columns
            FROM pg_class t
            JOIN pg_namespace n ON n.oid = t.relnamespace
            JOIN pg_index ix ON ix.indrelid = t.oid
            JOIN pg_class i ON i.oid = ix.indexrelid
            JOIN unnest(ix.indkey) WITH ORDINALITY AS k(attnum, ordinality)
              ON TRUE
            JOIN pg_attribute a
              ON a.attrelid = t.oid
             AND a.attnum = k.attnum
            WHERE n.nspname = %s
              AND t.relname = %s
            GROUP BY i.relname, ix.indisunique, ix.indisprimary;
        """, (self.sql.namespace, self.tablename))

    def _get_column_comments(self) -> list[dict[str, Any]]:
        return self.sql.fetchall("""
            SELECT a.attname AS column_name,
                   d.description AS comment
            FROM pg_class c
            JOIN pg_namespace n ON n.oid = c.relnamespace
            JOIN pg_attribute a ON a.attrelid = c.oid
            LEFT JOIN pg_description d
              ON d.objoid = c.oid
             AND d.objsubid = a.attnum
            WHERE n.nspname = %s
              AND c.relname = %s
              AND a.attnum > 0
              AND NOT a.attisdropped
            ORDER BY a.attnum;
        """, (self.sql.namespace, self.tablename))