from __future__ import annotations

from collections.abc import Callable, Mapping, Sized
from dataclasses import dataclass
from typing import Any

from .payload_validator import Scanner


Validator = Callable[[Any], bool]
DataType = type | tuple[type, ...]


@dataclass(slots=True)
class ValidationError:
    field: str | None
    code: str
    message: str
    expected: Any = None
    received: Any = None

    def as_dict(self) -> dict[str, Any]:
        return {
            "field": self.field,
            "code": self.code,
            "message": self.message,
            "expected": self.expected,
            "received": self.received,
        }


@dataclass(slots=True)
class Field:
    key: str

    required: bool = False
    nullable: bool = True

    datatype: DataType | None = None

    min_length: int | None = None
    max_length: int | None = None

    default: Any = None

    enum: list[Any] | tuple[Any, ...] | None = None

    scanner: Scanner | Validator | None = None

    autogenerated: bool = False
    readonly: bool = False


class ExpectedData:
    #Valida y captura un payload según campos declarados.
    def __init__(
        self,
        fields: Mapping[str, Field] | None = None,
    ) -> None:
        self.fields: dict[str, Field] = dict(fields or {})
        self._captured: dict[str, Any] = {}
        self._errors: list[ValidationError] = []

    def __iter__(self):
        return iter(self.fields.values())

    def add(self, field: Field) -> ExpectedData:
        if field.key in self.fields:
            raise ValueError(
                f"Field '{field.key}' duplicado"
            )

        self.fields[field.key] = field
        return self

    def scan(self, payload: Any) -> dict[str, Any]:
        self._captured = {}
        self._errors = []

        if payload is None:
            payload = {}

        if not isinstance(payload, Mapping):
            self._errors.append(
                ValidationError(
                    field=None,
                    code="INVALID_BODY",
                    message="Expected a mapping payload",
                    expected="mapping",
                    received=type(payload).__name__,
                )
            )
            return {}

        for field in self.fields.values():
            self._process_field(field, payload)

        return self.data()

    def validate(self, payload: Any) -> dict[str, Any]:
        self.scan(payload)

        return {
            "valid": self.is_valid(),
            "errors": self.errors(),
        }

    def _process_field(
        self,
        field: Field,
        payload: Mapping[str, Any],
    ) -> None:

        if field.key not in payload:
            if self._apply_default(field):
                return

            if self._is_required(field):
                self._add_error(
                    field,
                    code="required",
                    message="Field is required",
                    expected="present",
                    received="missing",
                )

            return

        value = payload[field.key]

        if value is None:
            if not field.nullable:
                self._add_error(
                    field,
                    code="nullable",
                    message="Field cannot be null",
                    expected="non-null",
                    received=None,
                )
                return

            self._captured[field.key] = None
            return

        error = self._validate_field(field, value)

        if error is not None:
            self._errors.append(error)
            return

        self._captured[field.key] = value

    def _apply_default(self, field: Field) -> bool:
        if field.default is None:
            return False

        value = (
            field.default()
            if callable(field.default)
            else field.default
        )

        self._captured[field.key] = value
        return True

    def _is_required(self, field: Field) -> bool:
        if field.required:
            return True

        if not field.nullable:
            if field.autogenerated or field.readonly:
                return False

            return field.default is None

        return False

    def _validate_field(
        self,
        field: Field,
        value: Any,
    ) -> ValidationError | None:

        if field.datatype is not None:
            if not self._matches_datatype(
                value,
                field.datatype,
            ):
                return self._make_error(
                    field,
                    "type",
                    "Invalid datatype",
                    expected=self._datatype_name(
                        field.datatype
                    ),
                    received=type(value).__name__,
                )

        if field.min_length is not None:
            if (
                isinstance(value, Sized)
                and len(value) < field.min_length
            ):
                return self._make_error(
                    field,
                    "min_length",
                    "Value is shorter than the minimum length",
                    expected=field.min_length,
                    received=len(value),
                )

        if field.max_length is not None:
            if (
                isinstance(value, Sized)
                and len(value) > field.max_length
            ):
                return self._make_error(
                    field,
                    "max_length",
                    "Value exceeds the maximum length",
                    expected=field.max_length,
                    received=len(value),
                )

        if field.enum is not None:
            if not self._choice_matches(
                value,
                field.enum,
            ):
                return self._make_error(
                    field,
                    "enum",
                    "Value is not one of the allowed choices",
                    expected=list(field.enum),
                    received=value,
                )

        return self._validate_scanner(field, value)

    def _validate_scanner(
        self,
        field: Field,
        value: Any,
    ) -> ValidationError | None:

        scanner = field.scanner

        if scanner is None:
            return None

        if isinstance(scanner, Scanner):
            try:
                result = scanner.validate(value)
            except Exception as exc:
                return self._make_error(
                    field,
                    "scanner",
                    "Scanner validation failed",
                    received=str(exc),
                )

            if not result.valido:
                return self._make_error(
                    field,
                    result.code or "INVALID_VALUE",
                    result.message or "Value rejected by scanner",
                    received=value,
                )

            return None

        if callable(scanner):
            try:
                valid = scanner(value)
            except Exception:
                valid = False

            if not valid:
                return self._make_error(
                    field,
                    "invalid_value",
                    "Value rejected by validator",
                    received=value,
                )

        return None

    @staticmethod
    def _matches_datatype(
        value: Any,
        datatype: DataType,
    ) -> bool:

        if datatype is int and isinstance(value, bool):
            return False

        if (
            isinstance(datatype, tuple)
            and isinstance(value, bool)
            and int in datatype
        ):
            datatype = tuple(
                t for t in datatype
                if t is not int
            )

        return isinstance(value, datatype)

    @staticmethod
    def _datatype_name(
        datatype: DataType,
    ) -> str:

        if isinstance(datatype, tuple):
            return " | ".join(
                t.__name__
                for t in datatype
            )

        return datatype.__name__

    @staticmethod
    def _choice_matches(
        value: Any,
        choices: list[Any] | tuple[Any, ...],
    ) -> bool:

        if isinstance(value, str):
            value_lower = value.lower()

            return any(
                str(choice).lower() == value_lower
                for choice in choices
            )

        return value in choices

    def _add_error(
        self,
        field: Field,
        code: str,
        message: str,
        expected: Any = None,
        received: Any = None,
    ) -> None:

        self._errors.append(
            self._make_error(
                field,
                code,
                message,
                expected,
                received,
            )
        )

    @staticmethod
    def _make_error(
        field: Field,
        code: str,
        message: str,
        expected: Any = None,
        received: Any = None,
    ) -> ValidationError:

        return ValidationError(
            field=field.key,
            code=code,
            message=message,
            expected=expected,
            received=received,
        )

    def errors(self) -> list[dict[str, Any]]:
        return [
            error.as_dict()
            for error in self._errors
        ]

    def is_valid(self) -> bool:
        return not self._errors

    def data(self) -> dict[str, Any]:
        return self._captured.copy()

    def result(self) -> dict[str, Any]:
        return {
            "valid": self.is_valid(),
            "data": self.data(),
            "errors": self.errors(),
        }